ekf_filter_node:
  ros__parameters:
    frequency: 20.0
    sensor_timeout: 0.5
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /encoder_odom
    odom0_config: [true, true, false,  # x, y, z
                   false, false, true,  # roll, pitch, yaw
                   true, false, false,  # vx, vy, vz
                   false, false, true,  # vroll, vpitch, vyaw
                   false, false, false] # ax, ay, az
    odom0_queue_size: 10
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: false

    odom1: /amcl_odom
    odom1_config: [true, true, false,  # x, y, z
                   false, false, true,  # roll, pitch, yaw
                   false, false, false, # vx, vy, vz
                   false, false, false, # vroll, vpitch, vyaw
                   false, false, false] # ax, ay, az
    odom1_queue_size: 10
    odom1_nodelay: false
    odom1_differential: false
    odom1_relative: false

    use_control: false
    publish_tf: true
    permit_corrected_publication: false